export const categories = [
  {
    id: '1',
    name: 'Waktu Pesta',
    description: 'Keseruan santai dengan tawa dan sedikit kekacauan — cocok untuk suasana grup apa pun!',
    icon: '🎉',
    color: '#FF6B6B',
  },
  {
    id: '2',
    name: 'Selebriti',
    description: 'Nama-nama terkenal dari film, musik, dan lainnya. Bertingkahlah seolah Anda tahu!',
    icon: '🌟',
    color: '#4ECDC4',
  },
  {
    id: '3',
    name: 'Makanan',
    description: 'Topik-topik lezat, tapi katakan hal yang salah dan Anda akan kalah!',
    icon: '🍕',
    color: '#FFD166',
  },
  {
    id: '4',
    name: 'Hollywood',
    description: 'Film, aktor, dan momen ikonik — berbohong dengan baik untuk tetap berada di adegan!',
    icon: '🎬',
    color: '#06D6A0',
  },
  {
    id: '5',
    name: 'Merek',
    description: 'Nama terkenal dan barang sehari-hari. Temukan — atau pura-pura tahu!',
    icon: '🏷️',
    color: '#118AB2',
  },
  {
    id: '6',
    name: 'Tempat',
    description: 'Negara, landmark, kota — bertingkahlah seolah Anda pernah ke sana!',
    icon: '🗺️',
    color: '#073B4C',
  },
  {
    id: '7',
    name: 'Hewan',
    description: 'Dari hewan peliharaan hingga binatang buas — bisakah Anda menyamar tanpa ketahuan?',
    icon: '🐾',
    color: '#EF476F',
  },
  {
    id: '8',
    name: 'Olahraga',
    description: 'Baik Anda penggemar atau pura-pura tahu, Anda perlu menjaga ekspresi tetap netral.',
    icon: '⚽',
    color: '#7209B7',
  },
  {
    id: '9',
    name: 'Pedas',
    description: 'Berani, nakal, sedikit berisiko — cocok untuk menciptakan ketegangan dan tawa!',
    icon: '🌶️',
    color: '#FF9E00',
  },
  {
    id: '10',
    name: 'Natal',
    description: 'Suasana meriah dan keajaiban musim dingin — bersantailah dan lihat siapa yang nakal atau baik!',
    icon: '🎄',
    color: '#1B9AAA',
  },
  {
    id: '11',
    name: 'Teknologi',
    description: 'Gadget, aplikasi, dan istilah teknis — tunjukkan pengetahuan atau berpura-puralah!',
    icon: '📱',
    color: '#3A86FF',
  },
  {
    id: '12',
    name: 'Musik',
    description: 'Artis, lagu, genre musik — apakah Anda tahu atau hanya berpura-pura?',
    icon: '🎵',
    color: '#8338EC',
  },
  {
    id: '13',
    name: 'Permainan',
    description: 'Video game, board game, dan karakter — dunia gaming menanti!',
    icon: '🎮',
    color: '#FF006E',
  },
  {
    id: '14',
    name: 'Sejarah',
    description: 'Peristiwa bersejarah, tokoh terkenal, dan penemuan penting.',
    icon: '📜',
    color: '#FB5607',
  },
  {
    id: '15',
    name: 'Sains',
    description: 'Fakta ilmiah, penemuan, dan istilah — uji pengetahuan Anda!',
    icon: '🔬',
    color: '#3A86FF',
  },
];

export default categories;